services:
  - type: web
    name: notes-backend
    env: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/notesBackend-0.0.1-SNAPSHOT.jar
    envVars:
      - key: PORT
        value: 8080
      - key: SPRING_PROFILES_ACTIVE
        value: production